/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './Paginator';
import * as i2 from './DataTable';
const styles_Paginator:any[] = ([] as any[]);
export const RenderType_Paginator:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Paginator,
    data:{}});
export function View_Paginator_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_Paginator_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'mfPaginator',
      ([] as any[]),(null as any),(null as any),(null as any),View_Paginator_0,RenderType_Paginator)),
      i0.ɵdid(573440,(null as any),0,i1.Paginator,[[2,i2.DataTable]],(null as any),
          (null as any))],(null as any),(null as any));
}
export const PaginatorNgFactory:i0.ComponentFactory<i1.Paginator> = i0.ɵccf('mfPaginator',
    i1.Paginator,View_Paginator_Host_0,{inputMfTable:'mfTable'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2dvYi9iaWxsY2FwL2FuZ3VsYXIyLWRhdGF0YWJsZS9zcmMvUGFnaW5hdG9yLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2dvYi9iaWxsY2FwL2FuZ3VsYXIyLWRhdGF0YWJsZS9zcmMvUGFnaW5hdG9yLnRzIiwibmc6Ly8vVXNlcnMvZ29iL2JpbGxjYXAvYW5ndWxhcjItZGF0YXRhYmxlL3NyYy9QYWdpbmF0b3IudHMuUGFnaW5hdG9yLmh0bWwiLCJuZzovLy9Vc2Vycy9nb2IvYmlsbGNhcC9hbmd1bGFyMi1kYXRhdGFibGUvc3JjL1BhZ2luYXRvci50cy5QYWdpbmF0b3JfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmctY29udGVudD48L25nLWNvbnRlbnQ+IiwiPG1mUGFnaW5hdG9yPjwvbWZQYWdpbmF0b3I+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OzJCQ0FBOzs7b0JDQUE7TUFBQTthQUFBO1VBQUE7OzsifQ==
